name: Manuel Alexis Silva Ruiz

on:
  workflow_dispatch:
    inputs:
      IMAGE_REPOSITORY:
        description: 'Repository of the image (same as declared in App Service creation)'
        required: true
        default: 'pds006'
      IMAGE_TAG:
        description: 'Tag of the image'
        required: true
        default: 'latest'
      AZURE_WEBAPP_NAME:
        description: 'Nombre del App Service creado en Azure'
        required: true
      PORT:
        description: 'Port of the application'
        default: '443'
        required: true

env:
  IMAGE_URL: ${{ secrets.ACR_NAME_MANUEL }}.azurecr.io/${{ github.event.inputs.IMAGE_REPOSITORY }}:${{ github.event.inputs.IMAGE_TAG }}

jobs:
  build-and-push-image:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME_MANUEL }}.azurecr.io
          username: ${{ secrets.ACR_NAME_MANUEL }}
          password: ${{ secrets.ACR_PASSWORD_MANUEL }}

      - name: Build and Push to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_URL }}
          file: Dockerfile

  deploy:
    name: 'Deploy remote container to Azure'
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Deploy to Azure Web App for Container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.event.inputs.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_MANUEL }}
          images: ${{ env.IMAGE_URL }}

  test-deploy:
    name: 'Test deployed service'
    runs-on: ubuntu-latest
    needs: [ build-and-push-image, deploy ]
    steps:
      - name: Checkout test assets
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            session.hurl
            tests/fixtures/test.png
          sparse-checkout-cone-mode: false

      # üß© Este paso ajusta din√°micamente las URLs internas
      # para que las llamadas a localhost:443 se redirijan
      # al host real con puerto 80 (sin tocar el c√≥digo ni session.hurl)
      - name: Replace localhost:443 with deployed host:80
        run: |
          sed -i "s|http://localhost:443|http://${{ github.event.inputs.AZURE_WEBAPP_NAME }}.azurewebsites.net:80|g" session.hurl

      - name: Setup hurl (API testing tool)
        uses: gacts/install-hurl@v1

      - name: Test API endpoints
        run: |
          hurl \
            --variable host=https://${{ github.event.inputs.AZURE_WEBAPP_NAME }}.azurewebsites.net:${{ github.event.inputs.PORT }} \
            --connect-timeout 20s \
            --error-format long \
            --verbose \
            --test session.hurl
